export const allProducts = [
  { id: 1, name: 'Prestige Deluxe Pressure Cooker 5L', imageUrl: 'https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT1e8R6n1KNgSWqn54XM2iN3987aAhdrpMKWIUhTAKbSiuX_WWEwRCQYv-0jOrPenVXienOFMTQioFl_lpJsRFumjhqpQiM', price: 1899, rating: 4.5, category: 'Kitchen Appliances' },
 { id: 2, name: 'Mixer Grinder', imageUrl: 'https://placehold.co/400x400?text=Mixer+Grinder', price: 2999, rating: 4.3, category: 'Kitchen Appliances' },
  { id: 3, name: 'Ceiling Fan', imageUrl: 'https://placehold.co/400x400?text=Ceiling+Fan', price: 1899, rating: 4.4, category: 'Home Appliances' },
  { id: 4, name: 'Water Purifier', imageUrl: 'https://placehold.co/400x400?text=Water+Purifier', price: 12999, rating: 4.6, category: 'Home Appliances' },
  { id: 5, name: 'Induction Cooktop', imageUrl: 'https://placehold.co/400x400?text=Induction+Cooktop', price: 1799, rating: 4.1, category: 'Kitchen Appliances' },
  { id: 6, name: 'Microwave Oven', imageUrl: 'https://placehold.co/400x400?text=Microwave+Oven', price: 11990, rating: 4.5, category: 'Kitchen Appliances' },
  { id: 7, name: 'Double Door Refrigerator', imageUrl: 'https://placehold.co/400x400?text=Refrigerator', price: 26990, rating: 4.6, category: 'Electronics' },
  { id: 8, name: 'Front Load Washing Machine', imageUrl: 'https://placehold.co/400x400?text=Washing+Machine', price: 27990, rating: 4.4, category: 'Home Appliances' },
  { id: 9, name: 'Split Air Conditioner', imageUrl: 'https://placehold.co/400x400?text=Split+AC', price: 32990, rating: 4.3, category: 'Cooling & Heating' },
  { id: 10, name: 'LED Smart TV', imageUrl: 'https://placehold.co/400x400?text=Smart+TV', price: 27999, rating: 4.7, category: 'Electronics' },
  { id: 11, name: 'Inverter with Battery', imageUrl: 'https://placehold.co/400x400?text=Inverter+Battery', price: 9999, rating: 4.2, category: 'Home Appliances' },
  { id: 12, name: 'Dry Iron', imageUrl: 'https://placehold.co/400x400?text=Dry+Iron', price: 799, rating: 4.0, category: 'Home Appliances' },
  { id: 13, name: 'Vacuum Cleaner', imageUrl: 'https://placehold.co/400x400?text=Vacuum+Cleaner', price: 5499, rating: 4.1, category: 'Home Appliances' },
  { id: 14, name: 'Room Heater', imageUrl: 'https://placehold.co/400x400?text=Room+Heater', price: 1299, rating: 3.9, category: 'Cooling & Heating' },
  { id: 15, name: 'Air Cooler', imageUrl: 'https://placehold.co/400x400?text=Air+Cooler', price: 6999, rating: 4.2, category: 'Cooling & Heating' },
  { id: 16, name: 'Electric Rice Cooker', imageUrl: 'https://placehold.co/400x400?text=Rice+Cooker', price: 1199, rating: 4.3, category: 'Kitchen Appliances' },
  { id: 17, name: 'Electric Kettle', imageUrl: 'https://placehold.co/400x400?text=Electric+Kettle', price: 699, rating: 4.0, category: 'Kitchen Appliances' },
  { id: 18, name: 'Kitchen Chimney', imageUrl: 'https://placehold.co/400x400?text=Kitchen+Chimney', price: 11999, rating: 4.4, category: 'Kitchen Appliances' },
  { id: 19, name: 'Storage Water Heater', imageUrl: 'https://placehold.co/400x400?text=Water+Heater', price: 8999, rating: 4.5, category: 'Cooling & Heating' },
  { id: 20, name: 'Smart Speaker', imageUrl: 'https://placehold.co/400x400?text=Smart+Speaker', price: 2499, rating: 4.6, category: 'Electronics' },
  { id: 21, name: 'Dual Band WiFi Router', imageUrl: 'https://placehold.co/400x400?text=WiFi+Router', price: 1799, rating: 4.2, category: 'Electronics' },
  { id: 22, name: 'Power Bank 20000mAh', imageUrl: 'https://placehold.co/400x400?text=Power+Bank', price: 1299, rating: 4.5, category: 'Electronics' },
  { id: 23, name: 'Beard Trimmer', imageUrl: 'https://placehold.co/400x400?text=Beard+Trimmer', price: 899, rating: 4.3, category: 'Personal Care' },
  { id: 24, name: 'Hair Dryer', imageUrl: 'https://placehold.co/400x400?text=Hair+Dryer', price: 599, rating: 3.8, category: 'Personal Care' },
  { id: 25, name: 'Sewing Machine', imageUrl: 'https://placehold.co/400x400?text=Sewing+Machine', price: 6499, rating: 4.4, category: 'Home Appliances' },
  { id: 26, name: 'Solar Water Heater', imageUrl: 'https://placehold.co/400x400?text=Solar+Heater', price: 15999, rating: 4.6, category: 'Cooling & Heating' },
  { id: 27, name: 'Juicer Mixer Grinder', imageUrl: 'https://placehold.co/400x400?text=Juicer+Mixer', price: 3499, rating: 4.5, category: 'Kitchen Appliances' },
  { id: 28, name: 'Pop-up Toaster', imageUrl: 'https://placehold.co/400x400?text=Pop-up+Toaster', price: 1099, rating: 4.0, category: 'Kitchen Appliances' },
  { id: 29, name: 'OTG Oven', imageUrl: 'https://placehold.co/400x400?text=OTG+Oven', price: 4999, rating: 4.3, category: 'Kitchen Appliances' },
  { id: 30, name: 'Steam Iron', imageUrl: 'https://placehold.co/400x400?text=Steam+Iron', price: 1499, rating: 4.1, category: 'Home Appliances' },
  { id: 32, name: 'Noise ColorFit Smart Watch', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcROUqkzAryjQ3ZfHQGQ3j1Ha5Xxp_tAwSWHfFDq7neZ1w&s=10', price: 2499, rating: 4.0, category: 'Electronics' },
  { id: 33, name: 'Godrej Almirah Steel Wardrobe', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSyDb8Q95bpAedofXQeCjGYPE0hwwwFChshcA7FMPEXRQ&s=10', price: 8999, rating: 4.4, category: 'Furniture' },
  { id: 34, name: 'Nilkamal Plastic Storage Cabinet', imageUrl: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRbaaHZolVTpoCuoJ_aAph5YmxvL3QZDGKGYfrLehVnkw&s', price: 3499, rating: 3.9, category: 'Furniture' },
  { id: 35, name: 'Wakefit Study Table with Storage', imageUrl: 'https://m.media-amazon.com/images/I/610DZzDRpSL._AC_UF894,1000_QL80_.jpg', price: 5999, rating: 4.5, category: 'Furniture' },
];